version: 0.2

env:
  variables:
    REPOSITORY_URI: 968176627785.dkr.ecr.us-east-1.amazonaws.com/frontend
    CONTAINER_NAME: frontend-container
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinition.json

artifacts:
  files:
    - imagedefinition.json
